apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: {{ .Values.cart.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: {{ .Values.cart.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/mycartdb
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: {{ .Values.cart.namespace }}
spec:
  selector:
    app: cart
  ports:
    - port: 5000
      targetPort: 5000